name: 'Bug Report'
description: 'Something is not working or has a problem'
title: '[Bug]'
body:
- type: markdown
  attributes:
    value: "## System Information"
- type: input
  id: platform
  attributes:
    label: Platform
    placeholder: 'Steam PC, Meta Quest, Android Device'
    description: 'What platform are you running on?'
  validations:
    required: true
- type: input
  id: OperatingSystem
  attributes:
    label: Operating System
    placeholder: 'Windows 10, Windows 11, Android, Linux'
    description: 'What operating system are you running on?'
  validations:
    required: true
- type: textarea
  id: problemmsg
  attributes:
    label: Describe the bug
  validations:
    required: true
